name: "Get changed files"
description: "Get changed files with based branch on PR or since last push"
author: "Maxim Samoilov (Nitive) <samoilowmaxim@gmail.com>"
inputs:
  files:
    required: false
    description: >
      File globs to include in results
    default: "**/*"
  token:
    required: false
    description: >
      Personal access token (PAT) used to make GitHub API calls
    default: ${{ github.token }}
outputs:
  files:
    description: >
      List of changed files or directories
  empty:
    description: >
      Set to true if no modified files or folders were found
runs:
  using: "node12"
  main: "dist/index.js"
