name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  milliseconds:
    required: false
    description: "input description here"
    default: "10"
runs:
  using: "node12"
  main: "dist/index.js"
