name: "build-test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build-test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make install
      - run: make lint
      - run: make test
