name: "e2e-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build
      - run: make install
      - run: make package

      # Test
      - uses: ./
        id: changed
        with:
          files: |
            src/*/

      - run: echo ${{ steps.changed.outputs.files }}

      # Publish
      - uses: EndBug/add-and-commit@v9
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          message: "Build action v2"
          add: "dist/ --force"
          tag: "v2 --force"
          push: "origin v2 --force"
